import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from './utils/tw-merge'
import Header from './components/layout/header'
import Footer from './components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={cn(inter.className, 'min-h-screen flex flex-col')}>
        <Header />
        <main className="flex-grow container mx-auto px-6">{children}</main>
        <Footer />
        {/* <Toaster /> */}
      </body>
    </html>
  )
}
