import { cn } from "@/utils/tw-merge";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import Login from "./login";
import PasswordScreen from "./password";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pediu Chegou",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body className={cn(inter.className, "min-h-screen flex flex-col")}>
        {/* <Header />
        <main className="flex-grow container mx-auto px-6">{children}</main>
        <Footer /> */}
        {/* <Login /> */}
        <PasswordScreen />
      </body>
    </html>
  );
}
